name: etugal_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  curved_navigation_bar: ^1.0.6
  dio: ^5.6.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  stylish_bottom_bar: ^1.1.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding/

  # fonts:
  #   - family: Signika
  #     fonts:
  #       - asset: assets/fonts/Signika-Regular.ttf
  #       - asset: assets/fonts/Signika-Bold.ttf
  #       - asset: assets/fonts/Signika-Light.ttf
  #       - asset: assets/fonts/Signika-Medium.ttf
  #       - asset: assets/fonts/Signika-SemiBold.ttf


flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

  # integrate colors here
  colors:
    inputs:
      - assets/color/colors.xml
